apiVersion: apps/v1
kind: Deployment
metadata:
  name: syncwave-app
  namespace: syncwave-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncwave-app
  template:
    metadata:
      labels:
        app: syncwave-app
    spec:
      containers:
      - name: supermario
        image: pengbai/docker-supermario
        ports:
        - containerPort: 8080
