apiVersion: v1
kind: Service
metadata:
  name: syncwave-service
  namespace: syncwave-namespace
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    app: syncwave-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
